export const INVALID_FIRST_NAME = "invalid_first_name";
export const INVALID_LAST_NAME = "invalid_last_name";
export const INVALID_AGE = "invalid_age";
export const INVALID_GENDER = "invalid_gender";
export const INVALID_NICK_NAME = "invalid_nick_name";
export const INVALID_EMAIL = "invalid_email";
export const INVALID_PASSWORD = "invalid_password";
export const INVALID_PASSWORD_2 = "invalid_password_2";
export const ERROR_ACCESSING_DATABASE = "error_accessing_database";
export const NO_USER_FOUND = "no_user_found";
export const ERROR_READING_DATA = "error_reading_data";
export const ERROR_PARSING_DATA = "error_parsing_data";
export const WRONG_METHOD = "error_wrong_method";
export const INVALID_INPUT = "invalid input";
export const AUTHORIZATION = "authorization";

export const host = 'http://localhost:8080/';
export const JSESSIONID = 'JSESSIONID';
export const ADMIN_JSESSIONID = 'ADMINJSESSIONID';